version: "3.8"

services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    image: app_image:latest
    depends_on:
      - db

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    networks:
      - app_network

    deploy:
      replicas: 2   # 🔥 Scaling
      restart_policy:
        condition: on-failure

volumes:
  db_data:

networks:
  app_network:
    driver: overlay
